### PR TITLE
Add ability to merge instead of just replacing existing store records

### LINKED ISSUE #29: Multiple loads of same object with different includes should merge relationships
Currently get of object will fully replace existing instance in the store. This may cause previously loaded relationships being lost. Example:
dispatch: get /article?include=author - will store author and article with rel=[author]
dispatch: get /article?include=comments - will store comments and article with rel=[comments], thus article.authror is not accessible anymore. this can also happen from includes/nested includes, for example:
dispatch get /authors?include=comments
dispatch get /artcles?include=author - will also replace author instance, thus all author comments won't be resolvable through author

I'd propose to improve add_records mutation to merge relationships of existing object from the store and new object.

PS: similar issue may happen when retreiving same object with different fields from different places, which will leave only last loaded fields in the store. Worth considering merging them as well.

### PR DESCRIPTION
**Pull request by mrichar1**
- Controlled by `mergeRecords` config option
- New mutations:
-- modifyRecords - merge or replace (config dependent)
-- replaceRecords - explicitly replace record
-- mergeRecords - explicitlymerge record
-- README updated to explain mutations
-- New tests for mutations and helper methods

Fixes #29

### CODE REVIEW

**Comment by mrichar1** [comment]
@staam hopefully this covers the needs form the original issue - I've left the default setting as `replace` rather than `merge` as it matches current behaviour, and because `merge` requires additional steps to keep data consistent in some cases.

Let me know what you think, and if you have any comments/requests - I hope to commit and release soon!

**Comment by staaam** [comment]
Hi, thanks for implementing this!
And it looks like exactly I've been thinking of, so looks good to me.
Will certainly give it a try once released.

**Comment by staaam** [comment]
The only thing that came to my mind - is changing the interface (addRecords -> modifyRecords), which might break some code (like mentioned here; https://github.com/mrichar1/jsonapi-vuex/issues/24). For me this change looks reasonable, maybe need to make appropriate versioning on release.

**Comment by mrichar1** [comment]
Thanks for that - yes keeping it as `addRecords` makes sense for backwards compatability. I've reverted it in the last commit (and merged on master to keep up-to-date).

**Comment by mrichar1** [comment]
Merged and released as `1.1.0`

**Comment by Stefano1990** [comment]
Is there any reasons why mergeRecords shouldn't default to true?

With ```mergeRecords = false``` you end up with code like this:
```javascript
computed: {
   posts () { return this.$store.getters['jv/get']('users', `$[?(@.userId == ${this.user.id})]`) }
}
```
Simply doing ```this.user.posts``` is not save since some nested component might return a user object as a relation. If that user object doesn't have the posts ```user.posts``` would become ```undefined```.

with ```mergeRecords = true``` you can simply do use ```this.user.posts``` which will never (?) become undefined.

**Comment by mrichar1** [comment]
The 'flipside' with defaulting to `true` is that since the merge is deep, you run the risk that the local store never removes data that has been dropped from the upstream API (in particular if your attributes contain nested data). For example: `_.merge({a:1, b:2}, {c:3})` will always 'grow' the object, even though the upstream value has dropped some keys.

Since both behaviours will be 'wrong' for a selection of users of the project, it wasn't clear which way to go on the default.  In the end, since the code base started with 'overwrite' being the default (merging only being added later) it was left this way so as to not cause breaking changes to anyone relying on that behaviour.

Of course the merge behaviour could be further customised, such as distinguishing between top-level and deep merges... feature requests always welcome!

**Pull request merged**
