### PR TITLE
Added flexibility to JSONAPI handling

### PR DESCRIPTION
**Pull request by iainsaxon**
* Skips loading relationships that have empty data values
* Checks if a URL is absolute before prefixing with the forward-slash
* Can add the relName to config for th getRelated action so that the links URLs can be used when passing in an object
* Allows a related data promise to return multiple items in the data object by always treating the promise data as an array

### CODE REVIEW

**Comment by iainsaxon** [comment]
@mrichar1, I've drafted a PR containing some changes that I needed to make to get this working for our JSONAPI implementation.

Because our routes are not using the Rails-style nested content paths (eg `/article/1/author`) I needed to alter the JS to better support the links that are sent from the server for an object when making subsequent requests in the getRelated store action.

I found that the get action can determine the correct URL to request related data if the first argument is an object and not a string (eg `/article/1/author`) however the relName value is not set and the getRelated action will not continue properly. In this PR there is an option to specify the relName in the config object passed to the getRelated action so that an object can still be used as the first argument.

When the getRelated did determine correct link URL it prefixed a forward-slash to the start of the URL even though it was an absolute URL so I've adjusted the getURL method to skip the prefix if its already applied or starts with "http".

Our to-many endpoints include all the results in the data node of the response and this seemed to be causing problems for the getRelated action where it was expecting to iterate over resource links and make a request for each entry. This would then return all the request promises to the next handler where it would build up the normData and add it to the object. Because we were returning an array of items in `[data]` and not a single object the data was not being mapped properly. This resulted in the value of `result` being an array of objects so there was no `[_jv][id]` or `[_jv][type]` to use when building up the related data object. I've altered the getRelated action so that it is always expecting to work on an array of promises containing an array of results (not a single result) and making it an array if a single result was returned.

There was also an issue where a null value for a relationship would still result in a request to the server so I've adjusted this behaviour too.

I can see that there are some items that I need to address during the build process to make it a valid PR and I'll try to address these soon.

In the meantime, are these alterations something you'd consider applicable and on the right track to be merged in?

Thanks.

**Comment by mrichar1** [comment]
Hi, Thanks for this PR!

I've not had a chance to think about the 'deep' stuff but the 'simple' things (like ignoring empty data values) seem to make sense. I should hopefully have time to properly review this PR in the next couple of days. (The travis failures are all simple 'prettier' tests that should be easy to resolve!)

**Comment by mrichar1** [comment]
Just took a few minutes to look at the URL slash issue - it actually appears that `axios` is clever enough to distinguish between `url` (i.e. path) being a full URL and a relative URL, and it adds a `/` automatically when there isn't one if needed. (See e.g. https://codepen.io/mrichar1/pen/mYYQqQ)

This means that the slash-adding code can be dropped entirely. I've created a new PR #67 to address this.

**Comment by mrichar1** [comment]
OK - So I had a little time just now after all to think about getRelated :smiley: 

Yes, it does appear that it currently isn't possible to provide an `object` as the argument to `getRelated` *and* also use relName to filter for one specific relationship.

Going back a step, if you're using `getRelated` with an `object` argument, this implies you have already done a `get` at least once. Might it make more sense that if getRelated is passed an object which already contains `relationship` data, that instead of (re)fetching the object from the API to populate its relationship data, it instead just uses the relationships already in the object? If nothing else this would make getRelated more efficient as it would involve one less fetch from the server.

In your case to get a single relationship, you would just provide an object with only the relationships in you were interested in. Or, if you wanted to use object but still `get` the object again, just don't populate it's relationships.

what do you think?

**Comment by mrichar1** [comment]
I've refactored `getRelated` to tidy it up and I believe add in the functionality you require, though implemented differently as explained above.

Please have a look and let me know if this approach and new 'features' solves the issues you were having!

**Comment by mrichar1** [comment]
Fixed (hopefully) by #72 - now merged in `2.0.0` release

**Pull request closed without merging**
