### PR TITLE
getRelated: relationship 'filtering'

### PR DESCRIPTION
**Pull request by mrichar1**
Alternative approach to fix the issues highlighted in #66 with `getRelated` filtering on relationships.

This PR adds new treatment of objects as the argument to `getRelated`.

As before, a 'simple' object causes that record to be fetched from the API, and it's relationships then processed.

If the object contains 'full' `_jv/relationships`, then this object is used instead of doing an API get.

If `_jv/relationships` only contains relationship names (i.e keys, but value === `undefined`), then the resource linkage is fetched from the API (`/type/id/relationships/relationshipName`) and used.

This allows a wider variety of ways to request none, some or all relationships be processed. It also makes `getRelated` more efficient if the record is already in the `store` as it prevents it being 're-fetched'.

### CODE REVIEW

**Comment by alexd73** [comment]
Hi! How to I must getting `items:` in my example?
```
{                                                                    
  _jv: {
    type: 'paragraph--items',
    id: 'c1393ca7-f6b9-42f3-985f-915ea2a54149',
    relationships: {
      paragraph_type: [Object],
      items: [Object]
    },
    links: {
      self: [Object]
    },
    isRel: [Function: isRel],
    isAttr: [Function: isAttr]
  },
  drupal_internal__id: 9,
  drupal_internal__revision_id: 403,
  langcode: 'ru',
  status: true,
  created: '2019-06-04T13:34:41+00:00',
  parent_id: '2',
  parent_type: 'node',
  parent_field_name: 'sections',
  behavior_settings: [],
  default_langcode: true,
  revision_translation_affected: null,
  body: {
  },
  subtitle: {
  },
  title: {
  },
  paragraph_type: {},
  items: {}
}


```

**Comment by mrichar1** [comment]
If you just wanted the `items` relationship, you could delete the other one from `relationships`, e.g.:

```
delete myObject['_jv']['relationships']['paragraph_type']
this.$store.dispatch('jv/getRelated', myObject)
```

**Comment by alexd73** [comment]
@mrichar1 I meant about empty `items` prop in first level restructured data.
why are they empty?

**Comment by alexd73** [comment]
@mrichar1 I guess I'm doing something wrong, but `items` is empty and sure it is associated with #73 

thist error when I call `jv/get` action (see my code bellow)
> WARN Cannot stringify a function isRel
> WARN Cannot stringify a function isAttr


Now I populate this items like this:

```
const paragraph = await dispatch(
      'jv/get',
      [`paragraph/${resType}/${uuid}`, { params: params }],
      { root: true }
    )
    if ('items' in paragraph._jv.relationships) {
      paragraph.items = paragraph._jv.relationships.items.data
    }
```

But I feel that this is the wrong way :)

**Comment by mrichar1** [comment]
Sorry for the delay in replying - have been away!

I'm going to dig into this - but I think the issue is to do with following relationships. My guess is that when the initial record is fetched, there are no relationships in the store, so although relationships are created at the top level, their value is set to an empty object.

After `getRelated` is run (or the related object comes into the store any other way) there's nothing that 'updates' the relationship data in the initial record.

A quick fix would be to update `getRelated` to cause relationships to be followed again - however I'd prefer it if there was some way that this could be dynamic. I'll have a think about how this works and see about implementing a fix.

**Comment by alexd73** [comment]
Hi! When I debuging I found problem (if I am not mistaken) in this line https://github.com/mrichar1/jsonapi-vuex/blob/master/src/jsonapi-vuex.js#L507 or in `followRelationships` jv had status `LADING` and in one of the following steps returned an empty object

**Pull request merged**
