### PR TITLE
Recursive followRelationships

### PR DESCRIPTION
**Pull request by staaam**

### CODE REVIEW

**Comment by mrichar1** [comment]
Thanks for this PR! I've not had a change to properly evaluate it yet - but a couple of thoughts:

1. Can we have a test that infinite recursion is protected against? Also do we need to test error paths (can a recursion throw any errors for missing related records etc?)

2. Is there a need to be able to limit recursion depth? i.e. to be able to disable recursion and just get the top-level related object.

3. @mhluska is currently overhauling the test suite in #27 , so might want to jump in on this when it's ready to ensure the tests meet the new setup.

**Comment by mrichar1** [comment]
The new approach with `checkAndFollowRelationships` looks good to me so I'm happy for this to be accepted (subject to the comments above).

Can I also ask you to add a line to `README.md` highlighting recursion, in the 'features' list at the top, and possible also in the 'Related Items' section?

**Comment by staaam** [comment]
> 
> Thanks for this PR! I've not had a change to properly evaluate it yet - but a couple of thoughts:
Thanks for quick responses (unfortunately, cannot keep the same) and great feedback. See answers inside.

>     1. Can we have a test that infinite recursion is protected against? Also do we need to test error paths (can a recursion throw any errors for missing related records etc?)
Actually one of the tests (should return normalized data with expanded rels (array)) needed to be fixed for recursive followRelationships, since the objects tested (norm_record_rels) already have recursive references (norm_widget_x: 1 -> 2, 2 -> 1 and 1 -> 2, 2 -> 3, 3 -> 1), so the infinite should be tested.

Regarding other errors - I cannot think about any cases (except for infinite call) which could be caused, since the only actual change in followRelationships is replacing clone() for nested object by recursive call to itself (which in turn will clone()), and managing follow_state which is "cloned" copy of subset of global state. So nothing specific to recursive change could be added in my opinion.

> 
>     2. Is there a need to be able to limit recursion depth? i.e. to be able to disable recursion and just get the top-level related object.
Interesting question. I'd say one would want a 0 expansion (followRelationships=false) or full expansion (followRelationships=true), and anything in the middle (even 1 level) will be probably very rare - in that case client's code will most probably have some kind of it's own traversal through different levels, thus also easy implementing traversal from 0 to needed level. 
It's very easy change on one hand, but will add one more "configuration parameter" which in my opinion better to push to later stage. It could be easily added if there will be enough use cases for recursion depth limit. What do you think?

> 
>     3. @mhluska is currently overhauling the test suite in #27 , so might want to jump in on this when it's ready to ensure the tests meet the new setup.

**Comment by staaam** [comment]
I've just pulled changes from master (after tests refactor) and having some issues with fixing the tests.. The test which was fixed before (should return normalized data with expanded rels (array)) is passing (which means something was changed in test), but have 3 other tests failing. And now have some issues fixing it - cannot create correct test data, since that causes an infinite recursion... Will need a closer look tomorrow.. 
@mhluska any idea how can I create a recursive test data (norm_widget_1_rels -> norm_widget_2_rels -> norm_widget_1_rels, (norm_widget_3_rels -> norm_widget_1_rels) ) ?
thanks

**Comment by mhluska** [comment]
Yeah, you could try something like this:

```js
const widget1 = createNormWidget1Rels();
const widget2 = createNormWidget2Rels()
widget1._jv.rels.widgets = widget2;
widget2._jv.rels.widgets = widget1;
```

Btw, I have a [PR out](https://github.com/mrichar1/jsonapi-vuex/pull/33) to fix an issue I was getting with infinite recursion in master. I have a hunch that if you pull that in, it might fix your issue with infinite recursion but not 100% sure.

**Comment by staaam** [comment]
Ok, so I've got tests fixed. Worth noting that currently all tests which check _rels widgets invoke recursive logic, due to test data structure (norm_widget_1_rels -> norm_widget_2_rels -> norm_widget_1_rels, (norm_widget_3_rels -> norm_widget_1_rels) )

**Comment by mrichar1** [comment]
Lgtm! Many thanks for this enhancement!

**Pull request merged**
