### PR TITLE
Add clearOnUpdate feature

### PR DESCRIPTION
**Pull request by mrichar1**
Provides for 2. in #55 

- Treat new data as 'definitive' (on a per-type basis).
- Remove old records from store during updateRecords()

### CODE REVIEW

**Comment by johanbaaij** [comment]
In `processIncludedRecords`, if an included type has multiple records only the last one will be in the store because in `updateRecords` `clearOnUpdate` is `true`.

Would it thelp if `clearOnUpdate` was a param for the `get` action (and following mutations)? This would be useful for clearing the results when you make a search API request and the following pages (like `GET /articles?page[number]=2`) can be added to the store.

**Comment by mrichar1** [comment]
Right - I'd forgotten that `includes` will be iterated over, resulting in multiple `updateRecords` calls.

It's tricky to parameterise actions, since `actrions` and `mutations` only takes a single argument. At the moment that argument is the `axios` config object - it could be refactored to take both `axios` and `jv` config - but that requires an overhaul of the module API which I'd prefer to avoid if there's another way to work round this.

Instead I've moved handling of `clearOnUpdate` into the `get` action and made it calla specific (new) `clearRecords` mutation. This means that `processIncludedRecords` and other similar functions that call mutations shouldn't ever perform this clear action. Let me know if this fixes things for you.

**Comment by johanbaaij** [comment]
Gotcha, I might even end up calling `clearRecords` in combination with `search` when I need it. I'd really like to preserve the store content for lists with a "Load more" button.

`clearRecords` does not clear anything for me, could that be because the records need to go through `normToStore`?

**Comment by mrichar1** [comment]
Ouch - it's not my week for coding! Not sure how I managed to change the test when moving it from using `normRecord` to `storeRecord` but you're completely right. Will fix shortly... Thanks for all the code review!

**Comment by johanbaaij** [comment]
Pleasure, I'll have a look at the new changes in the next couple of days.

**Pull request merged**
